/*
 * Created on 2018-09-27 ( Date ISO 2018-09-27 - Time 09:24:54 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.tlu.qlsuckhoe.repository;

import com.tlu.qlsuckhoe.entity.Benh;

import java.util.List;


import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Modifying;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;
import org.springframework.transaction.annotation.Transactional;

/**
 * Jpa repository for Benh.
 * @author Telosys (http://www.telosys.org/) version 3.0.0
 */
@Repository
public interface BenhRepository  extends JpaRepository<Benh, Integer> {
	@Query(value="Select * from benh limit :skip,:size",nativeQuery=true)
	List<Benh> findAllBenhWithPagination(@Param("skip") Integer skip,@Param("size") Integer size);
	@Query(value="Select * from benh where iddanhmuc = :iddanhmuc",nativeQuery=true)
	List<Benh> findAllBenhWithIddanhmuc(@Param("iddanhmuc") Integer iddanhmuc);
	@Query(value="delete from benh where idbenh = :idbenh",nativeQuery=true)
	@Transactional
	@Modifying
	void deleteById(@Param("idbenh") int idbenh);
}