/*
 * Created on 2018-09-27 ( Date ISO 2018-09-27 - Time 09:24:54 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.tlu.qlsuckhoe.repository;

import com.tlu.qlsuckhoe.entity.Danhmuc;

import java.util.List;

import javax.transaction.Transactional;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Modifying;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

/**
 * Jpa repository for Danhmuc.
 * @author Telosys (http://www.telosys.org/) version 3.0.0
 */
@Repository
public interface DanhmucRepository  extends JpaRepository<Danhmuc, Integer> {
	@Query(value="Select * from danhmuc limit :skip,:size",nativeQuery=true)
	List<Danhmuc> findAllDanhmucWithPagination(@Param("skip") Integer skip,@Param("size") Integer size);
	@Query(value="delete from danhmuc where iddanhmuc= :iddanhmuc",nativeQuery=true)
	@Transactional
	@Modifying
	void deleteById(@Param("iddanhmuc") Integer iddanhmuc);
}