/*
 * Created on 2018-09-27 ( Date ISO 2018-09-27 - Time 09:24:54 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.tlu.qlsuckhoe.repository;

import com.tlu.qlsuckhoe.entity.Dinhky;

//import com.tlu.qlsuckhoe.entity.Sinhvien;
import java.util.List;

import javax.transaction.Transactional;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Modifying;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

/**
 * Jpa repository for Dinhky.
 * @author Telosys (http://www.telosys.org/) version 3.0.0
 */
@Repository
public interface DinhkyRepository  extends JpaRepository<Dinhky, Integer> {
	
	@Query(value="Select * from dinhky k where k.idsinhvien = :idsinhvien and "
			+ "k.idhocki = :idhocki group by k.ngaykham Order by STR_TO_DATE(k.ngaykham,'%d/%m/%y') DESC",nativeQuery=true)
	List<Dinhky> findSvKhamByIdsinhvien(@Param("idsinhvien") int idsinhvien,@Param("idhocki") int idhocki);
	@Query(value="Select * from dinhky k group by k.ngaykham Order by STR_TO_DATE(k.ngaykham,'%d/%m/%y') DESC",nativeQuery=true)
	List<Dinhky> findAllngaykham();
	@Query(value="Select * from dinhky k where k.idhocki = :idhocki and k.idsinhvien in (select idsinhvien from sinhvien s where s.khoa = :khoa and s.chuyennganh = :chuyennganh) group by k.idsinhvien",nativeQuery=true)
	List<Dinhky> findAllIdsinhvien(@Param("idhocki") int idhocki,@Param("khoa") String khoa,@Param("chuyennganh") String chuyennganh);
	@Query(value="Select * from dinhky k where k.idsinhvien = :idsinhvien and "
			+ "k.idhocki = :idhocki and k.ngaykham = :ngaykham",nativeQuery=true)
	List<Dinhky> findSvKhamByNgayKham(@Param("idsinhvien") int idsinhvien,@Param("idhocki") int idhocki,@Param("ngaykham") String ngaykham);
	@Query(value="Select * from dinhky dk where dk.idsinhvien = :idsinhvien Group by dk.ngaykham Order by STR_TO_DATE(dk.ngaykham,'%d/%m/%y') DESC limit 1 ",nativeQuery=true)
	Dinhky findKetquaNew(@Param("idsinhvien") int idsinhvien);
	@Query(value="Select * from dinhky k where k.idhocki = :idhocki and "
			+ "k.idsinhvien in (select idsinhvien from sinhvien s where s.khoa = :khoa) group by k.ngaykham Order by STR_TO_DATE(k.ngaykham,'%d/%m/%y') DESC",nativeQuery=true)
	List<Dinhky> findDinhkyKhoaAndHocki(@Param("idhocki") int idhocki,@Param("khoa") String khoa);
	@Query(value="Select idbenh,count(idbenh) as soluong from dinhky k where k.idbenh not in (1,2,3,7) and k.idhocki = :idhocki "
			+ "and k.ngaykham in (select ngaykham FROM dinhky k1 where k1.idhocki = :idhocki group by k1.idsinhvien Order by STR_TO_DATE(k1.ngaykham,'%d/%m/%y') DESC) "
			+ "group by idbenh order by soluong DESC limit 3",nativeQuery=true)
	List<Object[]> findBenh(@Param("idhocki") int idhocki);
	@Query(value="select * FROM dinhky k1 where k1.idhocki = :idhocki group by k1.idsinhvien Order by STR_TO_DATE(k1.ngaykham,'%d/%m/%y') DESC",nativeQuery=true)
	List<Dinhky> CountSV(@Param("idhocki") int idhocki);
	@Query(value="select cannang/(chieucao*chieucao) from dinhky k "
			+ "where k.idhocki = :idhocki and k.idsinhvien in "
			+ "(select idsinhvien from sinhvien s where s.gioitinh='Nam') "
			+ "group by idsinhvien Order by STR_TO_DATE(ngaykham,'%d/%m/%y') DESC",nativeQuery=true)
	List<Object> CountBeophiNam(@Param("idhocki") int idhocki);
	@Query(value="select cannang/(chieucao*chieucao) from dinhky k "
			+ "where k.idhocki = :idhocki and k.idsinhvien in "
			+ "(select idsinhvien from sinhvien s where s.gioitinh='Nữ') "
			+ "group by idsinhvien Order by STR_TO_DATE(ngaykham,'%d/%m/%y') DESC",nativeQuery=true)
	List<Object> CountBeophiNu(@Param("idhocki") int idhocki);
	@Query(value="delete from dinhky where idkhamdinhky = :iddinhky",nativeQuery=true)
	@Transactional
	@Modifying
	void deleteById(@Param("iddinhky")int iddinhky);
}