/*
 * Created on 2018-09-27 ( Date ISO 2018-09-27 - Time 09:24:55 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.tlu.qlsuckhoe.repository;


import com.tlu.qlsuckhoe.entity.Hocki;

import java.util.List;

import javax.transaction.Transactional;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Modifying;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

/**
 * Jpa repository for Hocki.
 * @author Telosys (http://www.telosys.org/) version 3.0.0
 */
@Repository
public interface HockiRepository  extends JpaRepository<Hocki, Integer> {
	@Query(value="Select * from hocki limit :skip,:size",nativeQuery=true)
	List<Hocki> findAllHockiWithPagination(@Param("skip") Integer skip,@Param("size") Integer size);
	@Query(value="Select * from hocki order by right(tenhocki,4)",nativeQuery=true)
	List<Hocki> listHocki();
	@Query(value="Delete from hocki where idhocki = :idhocki",nativeQuery=true)
	@Transactional
	@Modifying
	void DeleteById(@Param("idhocki") Integer idhocki);
}