/*
 * Created on 2018-09-27 ( Date ISO 2018-09-27 - Time 09:24:55 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.tlu.qlsuckhoe.repository;

import com.tlu.qlsuckhoe.entity.Loaithuoc;
import java.util.List;

import javax.transaction.Transactional;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Modifying;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

/**
 * Jpa repository for Loaithuoc.
 * @author Telosys (http://www.telosys.org/) version 3.0.0
 */
@Repository
public interface LoaithuocRepository  extends JpaRepository<Loaithuoc, Integer> {
	@Query(value="Select * from loaithuoc limit :skip,:size",nativeQuery=true)
	List<Loaithuoc> findAllLoaithuocWithPagination(@Param("skip") Integer skip,@Param("size") Integer size);
	@Query(value="Delete from loaithuoc where idloaithuoc = :idloaithuoc",nativeQuery=true)
	@Transactional
	@Modifying
	void DeleteById(@Param("idloaithuoc") Integer idloaithuoc);
}