/*
 * Created on 2018-09-27 ( Date ISO 2018-09-27 - Time 09:24:55 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.tlu.qlsuckhoe.repository;

import com.tlu.qlsuckhoe.entity.Nhasanxuat;

import java.util.List;

import javax.transaction.Transactional;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Modifying;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

/**
 * Jpa repository for Nhasanxuat.
 * @author Telosys (http://www.telosys.org/) version 3.0.0
 */
@Repository
public interface NhasanxuatRepository  extends JpaRepository<Nhasanxuat, Integer> {
	@Query(value="Select * from nhasanxuat limit :skip,:size",nativeQuery=true)
	List<Nhasanxuat> findAllNhasanxuatWithPagination(@Param("skip") Integer skip,@Param("size") Integer size);
	@Query(value="Delete from nhasanxuat where idnhasanxuat = :idnhasanxuat",nativeQuery=true)
	@Transactional
	@Modifying
	void DeleteById(@Param("idnhasanxuat") Integer idnhasanxuat);
}