/*
 * Created on 2018-09-27 ( Date ISO 2018-09-27 - Time 09:24:56 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.tlu.qlsuckhoe.repository;

import com.tlu.qlsuckhoe.entity.Thuoc;
import java.util.List;

import javax.transaction.Transactional;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Modifying;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

/**
 * Jpa repository for Thuoc.
 * @author Telosys (http://www.telosys.org/) version 3.0.0
 */
@Repository
public interface ThuocRepository  extends JpaRepository<Thuoc, Integer> {
	@Query(value="Select * from thuoc limit :skip,:size",nativeQuery=true)
	List<Thuoc> findAllThuocWithPagination(@Param("skip") Integer skip,@Param("size") Integer size);
	@Query(value="Select * from thuoc where idloaithuoc = :idloaithuoc and idthuoc != 1",nativeQuery=true)
	List<Thuoc> findAllThuocByIdloaithuoc(@Param("idloaithuoc") int idloaithuoc);
	@Query(value="Select * from thuoc where idthuoc != 1",nativeQuery=true)
	List<Thuoc> findAllthuoc();
	@Query(value="Delete from thuoc where idthuoc = :idthuoc",nativeQuery=true)
	@Transactional
	@Modifying
	void deleteById(@Param("idthuoc")int idthuoc);
}