/*
 * Created on 2018-09-27 ( Date ISO 2018-09-27 - Time 09:24:57 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.tlu.qlsuckhoe.repository;

import com.tlu.qlsuckhoe.entity.Tintuc;

import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

/**
 * Jpa repository for Tintuc.
 * @author Telosys (http://www.telosys.org/) version 3.0.0
 */
@Repository
public interface TintucRepository  extends JpaRepository<Tintuc, Integer> {
	@Query(value="Select * from tintuc limit :skip,:size",nativeQuery=true)
	List<Tintuc> findAllTintucWithPagination(@Param("skip") Integer skip,@Param("size") Integer size);
}