/*
 * Created on 2018-09-27 ( Date ISO 2018-09-27 - Time 09:24:57 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.tlu.qlsuckhoe.repository;

import com.tlu.qlsuckhoe.entity.Yte;

import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Modifying;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;
import org.springframework.transaction.annotation.Transactional;

/**
 * Jpa repository for Yte.
 * @author Telosys (http://www.telosys.org/) version 3.0.0
 */
@Repository
public interface YteRepository  extends JpaRepository<Yte, Integer> {
	@Query(value="Select * from yte limit :skip,:size",nativeQuery=true)
	List<Yte> findAllYteWithPagination(@Param("skip") Integer skip,@Param("size") Integer size);
	@Query(value="Delete from yte where idyte = :idyte",nativeQuery=true)
	@Transactional
	@Modifying
	void deleteById(@Param("idyte") Integer idyte);
}