/*
 * Created on 2018-09-27 ( Date ISO 2018-09-27 - Time 09:24:54 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.tlu.qlsuckhoe.entity;

import java.io.Serializable;
import javax.persistence.*;

import org.hibernate.annotations.Proxy;

/**
 * Persistent class for Dinhky entity stored in table dinhky.
 * This class is a "record entity" without JPA links.
 * @author Telosys (http://www.telosys.org/) version 3.0.0
 */
@Entity
@Table(name="dinhky", catalog="qlsuckhoe" )
@Proxy(lazy=false)
public class Dinhky implements Serializable {

	private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="idkhamdinhky", nullable=false)
    private Integer idkhamdinhky ; 
    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @ManyToOne(fetch=FetchType.LAZY,cascade=CascadeType.ALL)
    @JoinColumn(name="idsinhvien")
    private Sinhvien sinhvien ; // Foreign Key     @Column(name="idhocki")
    @ManyToOne(fetch=FetchType.LAZY,cascade=CascadeType.ALL)
    @JoinColumn(name="idhocki")
    private Hocki hocki ; // Foreign Key     @Column(name="idbenh")
    @ManyToOne(fetch=FetchType.LAZY,cascade=CascadeType.ALL)
    @JoinColumn(name="idbenh")
    private Benh benh ; // Foreign Key
    private String ngaykham;
    @Column(name="chieucao", length=45)
    private float chieucao ;     @Column(name="cannang", length=45)
    private float cannang ;     @Column(name="huyetap", length=45)
    private int huyetap ;@Column(name="nhiptim", length=45)
    private int nhiptim;@Column(name="loaisuckhoe", length=45)
    private String loaisuckhoe ;     @Column(name="ketluan", length=45)
    private String ketluan ;     @Column(name="chuandoan", length=45)
    private String chuandoan ; 

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public Dinhky() {
		super();
    }

    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
	public void setIdkhamdinhky(Integer idkhamdinhky) {
        this.idkhamdinhky = idkhamdinhky ;
    }
	public Integer getIdkhamdinhky() {
        return this.idkhamdinhky;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
	//--- DATABASE MAPPING : idsinhvien (INT) 
	

	//--- DATABASE MAPPING : idhocki (INT) 
	public void setHocki(Hocki hocki) {this.hocki = hocki;}
	public Sinhvien getSinhvien() {
		return sinhvien;
	}

	public void setSinhvien(Sinhvien sinhvien) {
		this.sinhvien = sinhvien;
	}

	public Hocki getHocki() {return this.hocki;}

	//--- DATABASE MAPPING : idbenh (INT) 
	public void setBenh(Benh benh) {this.benh = benh;}
	public Benh getBenh() {return this.benh;}

	//--- DATABASE MAPPING : chieucao (VARCHAR) 
	

	//--- DATABASE MAPPING : loaisuckhoe (VARCHAR) 
	public void setLoaisuckhoe(String loaisuckhoe) {this.loaisuckhoe = loaisuckhoe;}
	public String getNgaykham() {
		return ngaykham;
	}

	public void setNgaykham(String ngaykham) {
		this.ngaykham = ngaykham;
	}

	public String getLoaisuckhoe() {return this.loaisuckhoe;}

	//--- DATABASE MAPPING : ketluan (VARCHAR) 
	public void setKetluan(String ketluan) {this.ketluan = ketluan;}
	public String getKetluan() {return this.ketluan;}

	//--- DATABASE MAPPING : chuandoan (VARCHAR) 
	public void setChuandoan(String chuandoan) {this.chuandoan = chuandoan;}
	public String getChuandoan() {return this.chuandoan;}

	

	public float getChieucao() {
		return chieucao;
	}

	public void setChieucao(float chieucao) {
		this.chieucao = chieucao;
	}

	public float getCannang() {
		return cannang;
	}

	public void setCannang(float cannang) {
		this.cannang = cannang;
	}

	public int getHuyetap() {
		return huyetap;
	}

	public void setHuyetap(int huyetap) {
		this.huyetap = huyetap;
	}

	public int getNhiptim() {
		return nhiptim;
	}

	public void setNhiptim(int nhiptim) {
		this.nhiptim = nhiptim;
	}

	//----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 	public String toString() {
		StringBuilder sb = new StringBuilder(); 
		sb.append(idkhamdinhky); 
		sb.append(sinhvien); 
		sb.append("|"); 
		sb.append(hocki); 
		sb.append("|"); 
		sb.append(benh); 
		sb.append("|"); 
		sb.append(chieucao); 
		sb.append("|"); 
		sb.append(cannang); 
		sb.append("|"); 
		sb.append(huyetap); 
		sb.append("|"); 
		sb.append(loaisuckhoe); 
		sb.append("|"); 
		sb.append(ketluan); 
		sb.append("|"); 
		sb.append(chuandoan); 
        return sb.toString();
    }
}