/*
 * Created on 2018-09-27 ( Date ISO 2018-09-27 - Time 09:24:55 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.tlu.qlsuckhoe.entity;

import java.io.Serializable;
import java.util.List;

import javax.persistence.*;

import org.hibernate.annotations.Proxy;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Persistent class for Role entity stored in table role.
 * This class is a "record entity" without JPA links.
 * @author Telosys (http://www.telosys.org/) version 3.0.0
 */
@Entity
@Table(name="role", catalog="qlsuckhoe" )
@Proxy(lazy=false)
public class Role implements Serializable {

	private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @Column(name="idrole", nullable=false)
    @GeneratedValue(strategy=GenerationType.AUTO)
    private Integer idrole ; 
    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="name", length=45)
    private String name ; 
    
    @OneToMany(fetch=FetchType.LAZY,cascade=CascadeType.ALL,mappedBy="role")
    @JsonIgnore
    private List<Yte> yte;
    @OneToMany(fetch=FetchType.LAZY,cascade=CascadeType.ALL,mappedBy="role")
    @JsonIgnore
    private List<Sinhvien> sinhvien;
    @OneToMany(fetch=FetchType.LAZY,cascade=CascadeType.ALL,mappedBy="role")
    @JsonIgnore
    private List<Admin> admin;
    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public Role() {
		super();
    }

    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
	public void setIdrole(Integer idrole) {
        this.idrole = idrole ;
    }
	public Integer getIdrole() {
        return this.idrole;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
	//--- DATABASE MAPPING : name (VARCHAR) 
	public void setName(String name) {this.name = name;}
	public String getName() {return this.name;}


    public List<Yte> getYte() {
		return yte;
	}

	public void setYte(List<Yte> yte) {
		this.yte = yte;
	}

	public List<Sinhvien> getSinhvien() {
		return sinhvien;
	}

	public void setSinhvien(List<Sinhvien> sinhvien) {
		this.sinhvien = sinhvien;
	}

	public List<Admin> getAdmin() {
		return admin;
	}

	public void setAdmin(List<Admin> admin) {
		this.admin = admin;
	}

	//----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 	public String toString() {
		StringBuilder sb = new StringBuilder(); 
		sb.append(idrole); 
		sb.append(name); 
        return sb.toString();
    }
}