/*
 * Created on 2018-09-27 ( Date ISO 2018-09-27 - Time 09:24:56 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.tlu.qlsuckhoe.entity;

import java.io.Serializable;
import javax.persistence.*;

import org.hibernate.annotations.Proxy;

/**
 * Persistent class for Sucosuckhoe entity stored in table sucosuckhoe.
 * This class is a "record entity" without JPA links.
 * @author Telosys (http://www.telosys.org/) version 3.0.0
 */
@Entity
@Table(name="sucosuckhoe", catalog="qlsuckhoe" )
@Proxy(lazy=false)
public class Sucosuckhoe implements Serializable {

	private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="idsucosuckhoe", nullable=false)
    private Integer idsucosuckhoe ; 
    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @ManyToOne(fetch=FetchType.LAZY,cascade=CascadeType.ALL)
    @JoinColumn(name="idsinhvien")
    private Sinhvien sinhvien ;// Foreign Key     @Column(name="ngay", length=45)
    private String ngay ;     @Column(name="loaisuco", length=45)
    private String loaisuco ;     @Column(name="bienphap", length=45)
    private String bienphap ;     @Column(name="mucdo", length=45)
    private String mucdo ;     @Column(name="nguoixuly", length=45)
    private String nguoixuly ;
    @ManyToOne(fetch=FetchType.LAZY,cascade=CascadeType.ALL)
    @JoinColumn(name="idthuoc")
    private Thuoc thuoc;
    @ManyToOne(fetch=FetchType.LAZY,cascade=CascadeType.ALL)
    @JoinColumn(name="idthietbiyte")
    private Thietbiyte thietbiyte ; 

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public Sucosuckhoe() {
		super();
    }

    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
	public void setIdsucosuckhoe(Integer idsucosuckhoe) {
        this.idsucosuckhoe = idsucosuckhoe ;
    }
	public Integer getIdsucosuckhoe() {
        return this.idsucosuckhoe;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
	//--- DATABASE MAPPING : idsinhvien (INT) 
	public void setSinhvien(Sinhvien sinhvien) {this.sinhvien = sinhvien;}
	public Sinhvien getSinhvien() {return this.sinhvien;}

	//--- DATABASE MAPPING : ngay (VARCHAR) 
	public void setNgay(String ngay) {this.ngay = ngay;}
	public String getNgay() {return this.ngay;}

	//--- DATABASE MAPPING : loaisuco (VARCHAR) 
	public void setLoaisuco(String loaisuco) {this.loaisuco = loaisuco;}
	public String getLoaisuco() {return this.loaisuco;}

	//--- DATABASE MAPPING : bienphap (VARCHAR) 
	public void setBienphap(String bienphap) {this.bienphap = bienphap;}
	public String getBienphap() {return this.bienphap;}

	//--- DATABASE MAPPING : mucdo (VARCHAR) 
	public void setMucdo(String mucdo) {this.mucdo = mucdo;}
	public String getMucdo() {return this.mucdo;}

	//--- DATABASE MAPPING : nguoixuly (VARCHAR) 
	public void setNguoixuly(String nguoixuly) {this.nguoixuly = nguoixuly;}
	public String getNguoixuly() {return this.nguoixuly;}

	//--- DATABASE MAPPING : idthuoc (INT) 
	public Thuoc getThuoc() {
		return thuoc;
	}

	public void setThuoc(Thuoc thuoc) {
		this.thuoc = thuoc;
	}
	//--- DATABASE MAPPING : idthietbiyte (INT) 
	public Thietbiyte getThietbiyte() {
		return thietbiyte;
	}

	public void setThietbiyte(Thietbiyte thietbiyte) {
		this.thietbiyte = thietbiyte;
	}

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 	public String toString() {
		StringBuilder sb = new StringBuilder(); 
		sb.append(idsucosuckhoe); 
		sb.append(sinhvien); 
		sb.append("|"); 
		sb.append(ngay); 
		sb.append("|"); 
		sb.append(loaisuco); 
		sb.append("|"); 
		sb.append(bienphap); 
		sb.append("|"); 
		sb.append(mucdo); 
		sb.append("|"); 
		sb.append(nguoixuly); 
		sb.append("|"); 
		sb.append(thuoc); 
		sb.append("|"); 
		sb.append(thietbiyte); 
        return sb.toString();
    }
}