/*
 * Created on 2018-09-27 ( Date ISO 2018-09-27 - Time 09:24:56 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.tlu.qlsuckhoe.entity;

import java.io.Serializable;
import java.util.List;

import javax.persistence.*;

import org.hibernate.annotations.Proxy;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Persistent class for Thietbiyte entity stored in table thietbiyte.
 * This class is a "record entity" without JPA links.
 * @author Telosys (http://www.telosys.org/) version 3.0.0
 */
@Entity
@Table(name="thietbiyte", catalog="qlsuckhoe" )
@Proxy(lazy=false)
public class Thietbiyte implements Serializable {

	private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="idthietbiyte", nullable=false)
    private Integer idthietbiyte ; 
    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------
    @ManyToOne(fetch=FetchType.LAZY,cascade=CascadeType.ALL)
	@JoinColumn(name="idnhasanxuat")
    private Nhasanxuat nhasanxuat;
    @OneToMany(fetch=FetchType.LAZY,cascade=CascadeType.ALL,mappedBy="thietbiyte")
    @JsonIgnore
    private List<Sucosuckhoe> sucosuckhoe;
    @Column(name="tenthietbi")
    private String tenthietbi ;
    @Column(name="ngaynhap")
    private String ngaynhap;
    @Column(name="soluong")
    private Integer soluong ;
    @Column(name="cachdung", length=45)
    private String cachdung ; 

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public Thietbiyte() {
		super();
    }

    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
	public void setIdthietbiyte(Integer idthietbiyte) {
        this.idthietbiyte = idthietbiyte ;
    }
	public Integer getIdthietbiyte() {
        return this.idthietbiyte;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
	//--- DATABASE MAPPING : idnhasanxuat (INT) 
	

	//--- DATABASE MAPPING : tenthietbi (VARCHAR) 
	public void setTenthietbi(String tenthietbi) {this.tenthietbi = tenthietbi;}
	public Nhasanxuat getNhasanxuat() {
		return nhasanxuat;
	}

	public void setNhasanxuat(Nhasanxuat nhasanxuat) {
		this.nhasanxuat = nhasanxuat;
	}

	public String getTenthietbi() {return this.tenthietbi;}
	
	public String getNgaynhap() {
		return ngaynhap;
	}
	public void setNgaynhap(String ngaynhap) {
		this.ngaynhap = ngaynhap;
	}

	//--- DATABASE MAPPING : soluong (INT) 
	public void setSoluong(Integer soluong) {this.soluong = soluong;}
	public Integer getSoluong() {return this.soluong;}

	//--- DATABASE MAPPING : cachdung (VARCHAR) 
	public void setCachdung(String cachdung) {this.cachdung = cachdung;}
	public String getCachdung() {return this.cachdung;}

	
    public List<Sucosuckhoe> getSucosuckhoe() {
		return sucosuckhoe;
	}

	public void setSucosuckhoe(List<Sucosuckhoe> sucosuckhoe) {
		this.sucosuckhoe = sucosuckhoe;
	}

	//----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 	public String toString() {
		StringBuilder sb = new StringBuilder(); 
		sb.append(idthietbiyte); 
		sb.append(nhasanxuat); 
		sb.append("|"); 
		sb.append(tenthietbi); 
		sb.append("|"); 
		sb.append(soluong); 
		sb.append("|"); 
		sb.append(cachdung); 
        return sb.toString();
    }
}