/*
 * Created on 2018-09-27 ( Date ISO 2018-09-27 - Time 09:24:56 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.tlu.qlsuckhoe.entity;

import java.io.Serializable;
import java.util.List;

import javax.persistence.*;

import org.hibernate.annotations.Proxy;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Persistent class for Thuoc entity stored in table thuoc.
 * This class is a "record entity" without JPA links.
 * @author Telosys (http://www.telosys.org/) version 3.0.0
 */
@Entity
@Table(name="thuoc", catalog="qlsuckhoe" )
@Proxy(lazy=false)
public class Thuoc implements Serializable {

	private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="idthuoc", nullable=false)
    private Integer idthuoc ; 
    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @ManyToOne(fetch=FetchType.LAZY,cascade=CascadeType.ALL)
    @JoinColumn(name="idloaithuoc")
    private Loaithuoc loaithuoc; // Foreign Key     @Column(name="idnhasanxuat")
    @ManyToOne(fetch=FetchType.LAZY,cascade=CascadeType.ALL)
    @JoinColumn(name="idnhasanxuat")
    private Nhasanxuat nhasanxuat;@Column(name="tenthuoc", length=45)
    private String tenthuoc ;     @Column(name="tacdung", length=45)
    private String tacdung ;     @Column(name="cachdung", length=45)
    private String cachdung ;     @Column(name="ngaynhap", length=45)
    private String ngaynhap ;     @Column(name="soluong")
    private Integer soluong ; 
    @OneToMany(fetch=FetchType.LAZY,cascade=CascadeType.ALL,mappedBy="thuoc")
    @JsonIgnore
    private List<Sucosuckhoe> sucosuckhoe;
    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public Thuoc() {
		super();
    }
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
	public void setIdthuoc(Integer idthuoc) {
        this.idthuoc = idthuoc ;
    }
	public Integer getIdthuoc() {
        return this.idthuoc;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
	//--- DATABASE MAPPING : idloaithuoc (INT) 
	

	//--- DATABASE MAPPING : tenthuoc (VARCHAR) 
	public void setTenthuoc(String tenthuoc) {this.tenthuoc = tenthuoc;}
	public Loaithuoc getLoaithuoc() {
		return loaithuoc;
	}

	public void setLoaithuoc(Loaithuoc loaithuoc) {
		this.loaithuoc = loaithuoc;
	}

	public Nhasanxuat getNhasanxuat() {
		return nhasanxuat;
	}

	public void setNhasanxuat(Nhasanxuat nhasanxuat) {
		this.nhasanxuat = nhasanxuat;
	}

	public String getTenthuoc() {return this.tenthuoc;}

	//--- DATABASE MAPPING : tacdung (VARCHAR) 
	public void setTacdung(String tacdung) {this.tacdung = tacdung;}
	public String getTacdung() {return this.tacdung;}

	//--- DATABASE MAPPING : cachdung (VARCHAR) 
	public void setCachdung(String cachdung) {this.cachdung = cachdung;}
	public String getCachdung() {return this.cachdung;}

	//--- DATABASE MAPPING : ngaynhap (VARCHAR) 
	public void setNgaynhap(String ngaynhap) {this.ngaynhap = ngaynhap;}
	public String getNgaynhap() {return this.ngaynhap;}

	//--- DATABASE MAPPING : soluong (INT) 
	public void setSoluong(Integer soluong) {this.soluong = soluong;}
	public Integer getSoluong() {return this.soluong;}
	

    public List<Sucosuckhoe> getSucosuckhoe() {
		return sucosuckhoe;
	}

	public void setSucosuckhoe(List<Sucosuckhoe> sucosuckhoe) {
		this.sucosuckhoe = sucosuckhoe;
	}

	//----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 	public String toString() {
		StringBuilder sb = new StringBuilder(); 
		sb.append(idthuoc); 
		sb.append(loaithuoc); 
		sb.append("|"); 
		sb.append(nhasanxuat); 
		sb.append("|"); 
		sb.append(tenthuoc); 
		sb.append("|"); 
		sb.append(tacdung); 
		sb.append("|"); 
		sb.append(cachdung); 
		sb.append("|"); 
		sb.append(ngaynhap); 
		sb.append("|"); 
		sb.append(soluong); 
        return sb.toString();
    }
}