/*
 * Created on 2018-09-27 ( Date ISO 2018-09-27 - Time 09:24:54 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.tlu.qlsuckhoe.service;



import java.util.List;

import com.tlu.qlsuckhoe.repository.BenhRepository;
import com.tlu.qlsuckhoe.service.criteria.BenhCriteria;
import com.tlu.qlsuckhoe.entity.Benh;
import com.tlu.qlsuckhoe.entity.PageResult;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Service
@Transactional(readOnly = true)
public class BenhServiceImpl implements BenhService {

	@Autowired
	private BenhRepository benhRepository;
	@Autowired
	private DanhmucServiceImpl danhmuc;

	@Override
	public Benh findById(Integer idbenh) {
		return benhRepository.findOne(idbenh);
	}

	@Override
	@Transactional
	public void delete(Integer idbenh) {
		benhRepository.deleteById(idbenh);
	}

	@Override
	@Transactional
	public Benh create(BenhCriteria benhToUpdate) {
		Benh benh = new Benh();
		benh.setTenbenh(benhToUpdate.getTenbenh());
		benh.setDanhmuc(danhmuc.findById(benhToUpdate.getIddanhmuc()));
		benh.setTrieuchung(benhToUpdate.getTrieuchung());
		benh.setCachchua(benhToUpdate.getCachchua());
		return benhRepository.save(benh);
	}

	@Override
	@Transactional
	public Benh update(int idbenh,BenhCriteria benhToUpdate) {
		Benh benh = findById(idbenh);
		benh.setTenbenh(benhToUpdate.getTenbenh());
		benh.setDanhmuc(danhmuc.findById(benhToUpdate.getIddanhmuc()));
		benh.setTrieuchung(benhToUpdate.getTrieuchung());
		benh.setCachchua(benhToUpdate.getCachchua());		
		return benhRepository.save(benh);
	}

	@Override
	public Boolean exist(Benh benh) {
		return benhRepository.exists(benh.getIdbenh());}
	@Override
	public List<Benh> findAll() {
		return benhRepository.findAll();
	}
	@Override
	public PageResult<Benh> search(int pageNo, int pageSize) {
		int skip=(pageNo-1)*pageSize;
		List<Benh> benh= benhRepository.findAllBenhWithPagination(skip, pageSize);
		int totalRecordCount=(int)benhRepository.count();
		return new PageResult<Benh>(benh, pageNo, pageSize, totalRecordCount);
	}

	@Override
	public List<Benh> findIddanhmuc(int iddanhmuc) {
		// TODO Auto-generated method stub
		return benhRepository.findAllBenhWithIddanhmuc(iddanhmuc);
	}

}

