/*
 * Created on 2018-09-27 ( Date ISO 2018-09-27 - Time 09:24:54 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.tlu.qlsuckhoe.service;

import com.tlu.qlsuckhoe.entity.Benh;
import com.tlu.qlsuckhoe.entity.PageResult;
import com.tlu.qlsuckhoe.service.criteria.BenhCriteria;

import java.util.List;

public interface BenhService {

	public Benh findById(Integer idbenh);

	public List<Benh> findAll();

	public void delete(Integer idbenh);

	public Benh create(BenhCriteria benh);

	public Benh update(int idbenh,BenhCriteria benh);
	
	public List<Benh> findIddanhmuc(int iddanhmuc);

	public Boolean exist(Benh benh);
	
	public PageResult<Benh> search(int pageNo,int pageSize);
}
