/*
 * Created on 2018-09-27 ( Date ISO 2018-09-27 - Time 09:24:54 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.tlu.qlsuckhoe.service;



import java.util.List;


import com.tlu.qlsuckhoe.repository.DanhmucRepository;
import com.tlu.qlsuckhoe.entity.Danhmuc;
import com.tlu.qlsuckhoe.entity.PageResult;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import javax.transaction.Transactional;

@Service
@Transactional
public class DanhmucServiceImpl implements DanhmucService {

	@Autowired
	private DanhmucRepository danhmucRepository;

	@Override
	public Danhmuc findById(Integer iddanhmuc) {
		return danhmucRepository.findOne(iddanhmuc);
	}

	@Override
	@Transactional
	public void delete(Integer iddanhmuc) {
		danhmucRepository.deleteById(iddanhmuc);
	}

	@Override
	@Transactional
	public Danhmuc create(Danhmuc danhmuc) {
		return danhmucRepository.save(danhmuc);
	}

	@Override
	@Transactional
	public Danhmuc update(int iddanhmuc,Danhmuc danhmucToUpdate) {
		Danhmuc danhmuc = findById(iddanhmuc);
		danhmuc.setTendanhmuc(danhmucToUpdate.getTendanhmuc());
		return danhmucRepository.save(danhmuc);
	}

	@Override
	public Boolean exist(Danhmuc danhmuc) {
		return danhmucRepository.exists(danhmuc.getIddanhmuc());
									}

	@Override
	public List<Danhmuc> findAll() {
		return danhmucRepository.findAll();
	}
	
	@Override
	public PageResult<Danhmuc> search(int pageNo, int pageSize) {
		int skip=(pageNo-1)*pageSize;
		List<Danhmuc> danhmuc= danhmucRepository.findAllDanhmucWithPagination(skip, pageSize);
		int totalRecordCount=(int)danhmucRepository.count();
		return new PageResult<Danhmuc>(danhmuc, pageNo, pageSize, totalRecordCount);
	}

	@Override
	@Transactional
	public void addList(List<Danhmuc> danhmuc) {
		danhmucRepository.save(danhmuc);
	}
}

