/*
 * Created on 2018-09-27 ( Date ISO 2018-09-27 - Time 09:24:54 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.tlu.qlsuckhoe.service;

import com.tlu.qlsuckhoe.entity.Dinhky;
import com.tlu.qlsuckhoe.service.criteria.ChisoBMI;
import com.tlu.qlsuckhoe.service.criteria.CountBenh1;
import com.tlu.qlsuckhoe.service.criteria.Dinhkyadd;
//import com.tlu.qlsuckhoe.service.criteria.Dinhkylist;
import com.tlu.qlsuckhoe.service.criteria.Dinhkylist;
import com.tlu.qlsuckhoe.service.criteria.Dinhkypost;

import java.util.List;

public interface DinhkyService {

	public Dinhky findById(Integer idkhamdinhky);

	public List<Dinhky> findAll();
	
	public Dinhky findKetquaNew(int idsinhvien);
	
	public void delete(Dinhkypost dk);

	public CountBenh1 countBenh(int idhocki);
	
	public ChisoBMI chisoBMI(int idhocki);
	
	public Dinhkyadd create(Dinhkyadd dinhky);

	public Dinhkypost update(Dinhkypost dinhky);
	
	public List<Dinhkylist> findSvKhamByIdsinhvien(int idsinhvien,int idhocki);
	
	public List<Dinhkylist> findSvKhamByHockiAndKhoa(int idhocki,String khoa,String chuyennganh);

	public Boolean exist(Dinhky dinhky);
}
