/*
 * Created on 2018-09-27 ( Date ISO 2018-09-27 - Time 09:24:54 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.tlu.qlsuckhoe.service;


import java.util.ArrayList;
import java.util.List;

import javax.transaction.Transactional;

import com.tlu.qlsuckhoe.repository.DinhkyRepository;
import com.tlu.qlsuckhoe.service.criteria.BenhId;
import com.tlu.qlsuckhoe.service.criteria.ChisoBMI;
import com.tlu.qlsuckhoe.service.criteria.CountBenh;
import com.tlu.qlsuckhoe.service.criteria.CountBenh1;
import com.tlu.qlsuckhoe.service.criteria.Dinhkyadd;
import com.tlu.qlsuckhoe.service.criteria.Dinhkylist;
import com.tlu.qlsuckhoe.service.criteria.Dinhkypost;
import com.tlu.qlsuckhoe.service.criteria.Ketqua;
import com.tlu.qlsuckhoe.service.criteria.Ketquapost;
import com.tlu.qlsuckhoe.service.criteria.NamBMI;
import com.tlu.qlsuckhoe.service.criteria.NuBMI;
import com.tlu.qlsuckhoe.entity.Dinhky;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

@Service
@Transactional
public class DinhkyServiceImpl implements DinhkyService {

	@Autowired
	private DinhkyRepository dinhkyRepository;
	@Autowired
	private SinhvienServiceImpl sinhvien;
	@Autowired
	private BenhServiceImpl benhService;
	@Autowired
	private HockiServiceImpl hocki;
	@Override
	public Dinhky findById(Integer idkhamdinhky) {
		return dinhkyRepository.findOne(idkhamdinhky);
	}

	@Override
	public List<Dinhky> findAll() {
		// TODO Auto-generated method stub
		return dinhkyRepository.findAll();
	}

	@Override
	@Transactional
	public void delete(Dinhkypost dk) {
		for(Ketquapost kq : dk.getKetqua()) {
			dinhkyRepository.deleteById(kq.getIddinhky());
		}
	}

	@Override
	@Transactional
	public Dinhkyadd create(Dinhkyadd dinhky) {
		for(BenhId benh:dinhky.getIdbenh())
		{
			Dinhky k=new Dinhky();
			k.setSinhvien(sinhvien.findById(dinhky.getIdsinhvien()));
			k.setBenh(benhService.findById(benh.getIdbenh()));
			k.setNgaykham(dinhky.getNgaykham());
			k.setCannang(dinhky.getCannang());
			k.setChieucao(dinhky.getChieucao());
			k.setChuandoan(benh.getChuandoan());
			k.setLoaisuckhoe(dinhky.getLoaisuckhoe());
			k.setNhiptim(dinhky.getNhiptim());
			k.setHuyetap(dinhky.getHuyetap());
			k.setHocki(hocki.findById(dinhky.getIdhocki()));
			k.setKetluan(dinhky.getKetluan());
			dinhkyRepository.save(k);
		}
		return dinhky;
	}
	@Override
	public List<Dinhkylist> findSvKhamByIdsinhvien(int idsinhvien, int idhocki) {
		List<Dinhkylist> dinhkyList = new ArrayList<>();
		List<Dinhky> lk=dinhkyRepository.findSvKhamByIdsinhvien(idsinhvien, idhocki);
		for(Dinhky dk1:lk)
		{
			List<Ketqua> ketqua=new ArrayList<Ketqua>();
			List<Dinhky> lk1=dinhkyRepository.findSvKhamByNgayKham(idsinhvien, idhocki,dk1.getNgaykham());
			Dinhkylist dinhky=new Dinhkylist();
			if(!lk1.isEmpty())
			{
				Dinhky dk=lk1.get(0);
				dinhky.setHoten(dk.getSinhvien().getHoten());
				dinhky.setMasv(dk.getSinhvien().getMasv());
				dinhky.setNgaykham(dk.getNgaykham());
				dinhky.setChieucao(dk.getChieucao());
				dinhky.setCannang(dk.getCannang());
				dinhky.setHuyetap(dk.getHuyetap());
				dinhky.setNhiptim(dk.getNhiptim());
				dinhky.setKetluan(dk.getKetluan());
				dinhky.setLoaisuckhoe(dk.getLoaisuckhoe());
				for(Dinhky k:lk1)
				{
					Ketqua kq=new Ketqua();
					kq.setIddinhky(k.getIdkhamdinhky());
					kq.setBenh(k.getBenh());
					kq.setChuandoan(k.getChuandoan());
					ketqua.add(kq);
				}
				dinhky.setKetqua(ketqua);
				dinhkyList.add(dinhky);
			}
		}
		return dinhkyList;
	}
	@Override
	@Transactional
	public Dinhkypost update(Dinhkypost dk) {
		for(Ketquapost kq : dk.getKetqua()) {
			Dinhky dinhky=findById(kq.getIddinhky());
			dinhky.setChieucao(dk.getChieucao());
			dinhky.setCannang(dk.getCannang());
			dinhky.setNgaykham(dk.getNgaykham());
			dinhky.setHuyetap(dk.getHuyetap());
			dinhky.setNhiptim(dk.getNhiptim());
			dinhky.setBenh(benhService.findById(kq.getIdbenh()));
			dinhky.setChuandoan(kq.getChuandoan());
			dinhky.setKetluan(dk.getKetluan());
			dinhky.setLoaisuckhoe(dk.getLoaisuckhoe());
			dinhkyRepository.save(dinhky);
		}
		return dk;
	}
	@Override
	public Boolean exist(Dinhky dinhky) {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public Dinhky findKetquaNew(int idsinhvien) {
		// TODO Auto-generated method stub
		return dinhkyRepository.findKetquaNew(idsinhvien);
	}

	@Override
	public List<Dinhkylist> findSvKhamByHockiAndKhoa(int idhocki, String khoa,String chuyennganh) {
		List<Dinhkylist> dinhkyList = new ArrayList<>();
		List<Dinhky> ngaykham=dinhkyRepository.findAllngaykham();
		List<Dinhky> sinhvien=dinhkyRepository.findAllIdsinhvien(idhocki, khoa,chuyennganh);
		for(Dinhky nk:ngaykham)
		{
			for(Dinhky dk1:sinhvien)
			{
				List<Ketqua> ketqua=new ArrayList<Ketqua>();
				Dinhkylist dinhky=new Dinhkylist();
				List<Dinhky> lk1=dinhkyRepository.findSvKhamByNgayKham(dk1.getSinhvien().getIdsinhvien(), idhocki,nk.getNgaykham());
				if(!lk1.isEmpty())
				{
					Dinhky dk=lk1.get(0);
					dinhky.setHoten(dk.getSinhvien().getHoten());
					dinhky.setMasv(dk.getSinhvien().getMasv());
					dinhky.setNgaykham(dk.getNgaykham());
					dinhky.setChieucao(dk.getChieucao());
					dinhky.setCannang(dk.getCannang());
					dinhky.setHuyetap(dk.getHuyetap());
					dinhky.setNhiptim(dk.getNhiptim());
					dinhky.setKetluan(dk.getKetluan());
					dinhky.setLoaisuckhoe(dk.getLoaisuckhoe());
					for(Dinhky k:lk1)
					{
						Ketqua kq=new Ketqua();
						kq.setIddinhky(k.getIdkhamdinhky());
						kq.setBenh(k.getBenh());
						kq.setChuandoan(k.getChuandoan());
						ketqua.add(kq);
					}
					dinhky.setKetqua(ketqua);
					dinhkyList.add(dinhky);
				}
			}
		}
		return dinhkyList;
	}

	@Override
	public CountBenh1 countBenh(int idhocki) {
		List<CountBenh> cb=new ArrayList<>();
		CountBenh1 cb1=new CountBenh1();
		for(Object[] a:dinhkyRepository.findBenh(idhocki)) {
			CountBenh c= new CountBenh();
			c.setIdbenh(((Number) a[0]).intValue());
			c.setTenbenh(benhService.findById(c.getIdbenh()).getTenbenh());
			c.setSoluong(((Number) a[1]).intValue());
			cb.add(c);
		}
		cb1.setBenh(cb);
		cb1.setTong(((Number)dinhkyRepository.CountSV(idhocki).size()).intValue());
		return cb1;
	}

	@Override
	public ChisoBMI chisoBMI(int idhocki) {
		int beophi=0,bp=0;
		int gay=0,g=0;
		int binhthuong=0,bt=0;
		ChisoBMI cs= new ChisoBMI();
		NamBMI na=new NamBMI();
		NuBMI nu=new NuBMI();
		for(Object a:dinhkyRepository.CountBeophiNam(idhocki)) {
			float t=((Number) a).floatValue();
			if(t<18.5) {
				gay+=1;
			}
			else if(t>=25) {beophi+=1;}
			else {
				binhthuong+=1;
			}
		}
		na.setBeophi(beophi);
		na.setBinhthuong(binhthuong);
		na.setGay(gay);
		for(Object a:dinhkyRepository.CountBeophiNu(idhocki)) {
			float t=((Number) a).floatValue();
			if(t<18.5) {
				g+=1;
			}
			else if(t>=25) {bp+=1;}
			else {
				bt+=1;
			}
		}
		nu.setBeophi(bp);
		nu.setGay(g);
		nu.setBinhthuong(bt);
		cs.setNam(na);
		cs.setNu(nu);
		cs.setTong(((Number)dinhkyRepository.CountSV(idhocki).size()).intValue());
		return cs;
	}
}

