/*
 * Created on 2018-09-27 ( Date ISO 2018-09-27 - Time 09:24:55 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.tlu.qlsuckhoe.service;

import com.tlu.qlsuckhoe.entity.Hocki;
import com.tlu.qlsuckhoe.entity.PageResult;

import java.util.List;

public interface HockiService {

	public Hocki findById(Integer idhocki);

	public List<Hocki> findAll();

	public void delete(Integer idhocki);

	public Hocki create(Hocki hocki);
	
	public void addHocki(List<Hocki> hocki);
	
	public Hocki update(int idhocki,Hocki hocki);

	public Boolean exist(Hocki hocki);
	
	public PageResult<Hocki> search(int pageNo,int pageSize);
}
