/*
 * Created on 2018-09-27 ( Date ISO 2018-09-27 - Time 09:24:55 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.tlu.qlsuckhoe.service;

import com.tlu.qlsuckhoe.entity.Nhasanxuat;
import com.tlu.qlsuckhoe.entity.PageResult;

import java.util.List;

public interface NhasanxuatService {

	public Nhasanxuat findById(Integer idnhasanxuat);

	public List<Nhasanxuat> findAll();

	public void delete(Integer idnhasanxuat);

	public Nhasanxuat create(Nhasanxuat nhasanxuat);
	public void addList(List<Nhasanxuat> nhasanxuat);

	public void update(int idnhasanxuat,Nhasanxuat nhasanxuat);

	public Boolean exist(Nhasanxuat nhasanxuat);
	
	public PageResult<Nhasanxuat> search(int pageNo,int pageSize);
}
