/*
 * Created on 2018-09-27 ( Date ISO 2018-09-27 - Time 09:24:55 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.tlu.qlsuckhoe.service;



import java.util.List;

import javax.transaction.Transactional;

import com.tlu.qlsuckhoe.repository.NhasanxuatRepository;
import com.tlu.qlsuckhoe.entity.Nhasanxuat;
import com.tlu.qlsuckhoe.entity.PageResult;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

@Service
@Transactional
public class NhasanxuatServiceImpl implements NhasanxuatService {

	@Autowired
	private NhasanxuatRepository nhasanxuatRepository;

	@Override
	public Nhasanxuat findById(Integer idnhasanxuat) {
		return nhasanxuatRepository.findOne(idnhasanxuat);
	}

	@Override
	@Transactional
	public void delete(Integer idnhasanxuat) {
		nhasanxuatRepository.DeleteById(idnhasanxuat);
	}

	@Override
	public Nhasanxuat create(Nhasanxuat nhasanxuat) {
		return nhasanxuatRepository.save(nhasanxuat);
	}

	@Override
	@Transactional
	public void update(int idnhasanxuat,Nhasanxuat nhasanxuatToUpdate) {
		Nhasanxuat nhasanxuat = findById(idnhasanxuat);
		nhasanxuat.setTennhasanxuat(nhasanxuatToUpdate.getTennhasanxuat());
		nhasanxuatRepository.save(nhasanxuat);
	}

	@Override
	public Boolean exist(Nhasanxuat nhasanxuat) {
						return nhasanxuatRepository.exists(nhasanxuat.getIdnhasanxuat());
									}

	@Override
	public List<Nhasanxuat> findAll() {
		return nhasanxuatRepository.findAll();
	}

	@Override
	public PageResult<Nhasanxuat> search(int pageNo, int pageSize) {
		int skip=(pageNo-1)*pageSize;
		List<Nhasanxuat> nhasx= nhasanxuatRepository.findAllNhasanxuatWithPagination(skip, pageSize);
		int totalRecordCount=(int)nhasanxuatRepository.count();
		return new PageResult<Nhasanxuat>(nhasx, pageNo, pageSize, totalRecordCount);
	}

	@Override
	@Transactional
	public void addList(List<Nhasanxuat> nhasanxuat) {
		nhasanxuatRepository.save(nhasanxuat);
		
	}
}

