/*
 * Created on 2018-09-27 ( Date ISO 2018-09-27 - Time 09:24:56 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.tlu.qlsuckhoe.service;



import java.util.ArrayList;
import java.util.List;

import com.tlu.qlsuckhoe.entity.Chuyennganh;
import com.tlu.qlsuckhoe.entity.Khoa;
//import com.tlu.qlsuckhoe.entity.Khoa;
import com.tlu.qlsuckhoe.entity.PageResult;
import com.tlu.qlsuckhoe.entity.Sinhvien;
import com.tlu.qlsuckhoe.repository.RoleRepository;
import com.tlu.qlsuckhoe.repository.SinhvienRepository;
import com.tlu.qlsuckhoe.service.criteria.SinhvienCriteria;
import com.tlu.qlsuckhoe.service.criteria.SinhvienPost;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Service
@Transactional(readOnly = true)
public class SinhvienServiceImpl implements SinhvienService {

	@Autowired
	private SinhvienRepository sinhvienRepository;
	@Autowired
	private RoleRepository roleRepository; 
	@Override
	public Sinhvien findById(Integer idsinhvien) {
		return sinhvienRepository.findOne(idsinhvien);
	}
	@Override
	@Transactional
	public void delete(Integer idsinhvien) {
		sinhvienRepository.deleteById(idsinhvien);
	}
	@Override
	public Boolean exist(Sinhvien sinhvien) {
						return sinhvienRepository.exists(sinhvien.getIdsinhvien());
																																													}

	@Override
	public List<Sinhvien> findAll() {
		return sinhvienRepository.findAll();
	}
	@Override
	@Transactional
	public List<Khoa> findAllKhoa() {
		List<Khoa> k = new ArrayList<Khoa>();
		for (Sinhvien khoa : sinhvienRepository.findAllKhoa()) {
			Khoa k1= new Khoa();
			k1.setKhoa(khoa.getKhoa());
			k.add(k1);
		}
		return k;
	}
	@Override
	public Sinhvien create(SinhvienCriteria sinhvien) {
		// TODO Auto-generated method stub
		return null;
	}
	@Override
	@Transactional
	public Sinhvien update(int idsinhvien, SinhvienCriteria sinhvien) {
		Sinhvien s = findById(idsinhvien);
		s.setHoten(sinhvien.getHoten());
		s.setDiachi(sinhvien.getDiachi());
		s.setChuyennganh(sinhvien.getChuyennganh());
		s.setGioitinh(sinhvien.getGioitinh());
		s.setKhoa(sinhvien.getKhoa());
		s.setSocmt(sinhvien.getSocmt());
		s.setMasv(sinhvien.getMasv());
		s.setMatkhau(sinhvien.getMatkhau());
		s.setNamsinh(sinhvien.getNamsinh());
		sinhvienRepository.save(s);
		return s;
	}
	@Override
	public List<Sinhvien> searchKhoa(String khoa) {
		return sinhvienRepository.findAllSinhvienWithKhoa(khoa);
	}
	@Override
	public PageResult<Sinhvien> searchKhoaPagination(String khoa, int pageNo, int pageSize) {
		int skip=(pageNo-1)*pageSize;
		List<Sinhvien> sinhvien= sinhvienRepository.findAllSinhvienWithKhoaPagination(khoa, skip, pageSize);
		int totalRecordCount=sinhvienRepository.findAllSinhvienWithKhoa(khoa).size();
		return new PageResult<Sinhvien>(sinhvien, pageNo, pageSize, totalRecordCount);
	}
	@Override
	public PageResult<Sinhvien> seacrh(int pageNo, int pageSize) {
		int skip=(pageNo-1)*pageSize;
		List<Sinhvien> sinhvien= sinhvienRepository.findAllSinhvienWithPagination(skip,pageSize);
		int totalRecordCount=(int)sinhvienRepository.count();
		return new PageResult<Sinhvien>(sinhvien, pageNo, pageSize, totalRecordCount);
	}
	@Override
	public Sinhvien searchMaten(String maten) {
		return sinhvienRepository.findSinhvienMasvTen(maten);
	}
	@Override
	public List<Sinhvien> findSinhvienByIdhk(String khoa, int idhocki) {
		// TODO Auto-generated method stub
		return sinhvienRepository.findSvChuaKhamByHockiAndKhoa(khoa, idhocki);
	}
	@Override
	public PageResult<Sinhvien> findSinhvienByIdhkPage(String khoa, int idhocki, int pageNo, int pageSize) {
		int skip=(pageNo-1)*pageSize;
		List<Sinhvien> sinhvien=sinhvienRepository.findSvChuaKhamPaginationByHockiAndKhoa(khoa, idhocki, skip, pageSize);
		int totalRecordCount=findSinhvienByIdhk(khoa, idhocki).size();
		return new PageResult<Sinhvien>(sinhvien,pageNo,pageSize,totalRecordCount);
	}
	@Override
	public List<Sinhvien> findSvChuaKhamByHockiKhoaMaten(String khoa, int idhocki, String maten) {
		// TODO Auto-generated method stub
		return sinhvienRepository.findSvChuaKhamByHockiKhoaMaten(khoa, idhocki, maten);
	}
	@Override
	@Transactional
	public SinhvienPost addListsv(List<SinhvienPost> listsv) {
		for(SinhvienPost sv:listsv)
		{
			Sinhvien s= new Sinhvien();
			s.setHoten(sv.getHoten());
			s.setGioitinh(sv.getGioitinh());
			s.setNamsinh(sv.getNamsinh());
			s.setDiachi(sv.getDiachi());
			s.setSocmt(sv.getSocmt());
			s.setChuyennganh(sv.getChuyennganh());
			s.setKhoa(sv.getKhoa());
			s.setMasv(sv.getMasv());
			s.setMatkhau("123456");
			s.setRole(roleRepository.findOne(2));
			sinhvienRepository.save(s);
		}
		return null;
	}
	@Override
	public List<Chuyennganh> findAllChuyennganh() {
		List<Chuyennganh> cn = new ArrayList<Chuyennganh>();
		for (Sinhvien khoa : sinhvienRepository.findAllChuyennganh()) {
			Chuyennganh k1= new Chuyennganh();
			k1.setChuyennganh(khoa.getChuyennganh());
			cn.add(k1);
		}
		return cn;
	}
	@Override
	public List<Sinhvien> findSinhvienByCn(String khoa, String chuyennganh) {
		return sinhvienRepository.findByChuyennganhAndKhoa(khoa, chuyennganh);
	}
	@Override
	@Transactional
	public void changePass(int idsinhvien, String passWorld) {
		Sinhvien s = sinhvienRepository.findOne(idsinhvien);
		s.setMatkhau(passWorld);
		sinhvienRepository.save(s);
	}

}

