/*
 * Created on 2018-09-27 ( Date ISO 2018-09-27 - Time 09:24:56 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.tlu.qlsuckhoe.service;

import com.tlu.qlsuckhoe.entity.Chuyennganh;
import com.tlu.qlsuckhoe.entity.Khoa;
import com.tlu.qlsuckhoe.entity.PageResult;
import com.tlu.qlsuckhoe.entity.Sinhvien;
import com.tlu.qlsuckhoe.service.criteria.SinhvienCriteria;
import com.tlu.qlsuckhoe.service.criteria.SinhvienPost;

import java.util.List;

public interface SinhvienService {

	public Sinhvien findById(Integer idsinhvien);

	public List<Sinhvien> findAll();
	
	public List<Khoa> findAllKhoa();
	
	public void delete(Integer idsinhvien);

	public Sinhvien create(SinhvienCriteria sinhvien);
	public SinhvienPost addListsv(List<SinhvienPost> listsv);
	public Sinhvien update(int idsinhvien,SinhvienCriteria sinhvien);
	public List<Chuyennganh> findAllChuyennganh();
	public List<Sinhvien> searchKhoa(String khoa);
	public Sinhvien searchMaten(String maten);
	public void changePass(int idsinhvien,String passWorld);
	public PageResult<Sinhvien> searchKhoaPagination(String khoa,int pageNo,int pageSize);
	public PageResult<Sinhvien> seacrh(int pageNo,int pageSize);
	public List<Sinhvien> findSinhvienByCn(String khoa,String chuyennganh);
	public List<Sinhvien> findSinhvienByIdhk(String khoa,int idhocki);
	public PageResult<Sinhvien> findSinhvienByIdhkPage(String khoa,int idhocki,int pageNo,int pageSize);
	public List<Sinhvien> findSvChuaKhamByHockiKhoaMaten(String khoa,int idhocki,String maten);
	public Boolean exist(Sinhvien sinhvien);
}
