/*
 * Created on 2018-09-27 ( Date ISO 2018-09-27 - Time 09:24:56 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.tlu.qlsuckhoe.service;

import com.tlu.qlsuckhoe.entity.Sucosuckhoe;
import com.tlu.qlsuckhoe.service.criteria.Sucosuckhoeadd;
import com.tlu.qlsuckhoe.service.criteria.Sucosuckhoelist;

import java.util.List;

public interface SucosuckhoeService {

	public Sucosuckhoe getOne(Integer idsucosuckhoe);

	public List<Sucosuckhoe> findAll();

	public void delete(int idsinhvien,String ngay);

	public Sucosuckhoeadd create(Sucosuckhoeadd sucosuckhoe);

	public void update(int idsinhvien,String ngay,Sucosuckhoeadd sucosuckhoe);

	public Boolean exist(Sucosuckhoe sucosuckhoe);
	
	public List<Sucosuckhoelist> findAllSuco(String khoa);
	
	public Sucosuckhoelist findBySinhVien(int idsinhvien,String ngay);
	
	public List<Sucosuckhoelist> findBySV(int idsinhvien);
}
