/*
 * Created on 2018-09-27 ( Date ISO 2018-09-27 - Time 09:24:56 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.tlu.qlsuckhoe.service;

import com.tlu.qlsuckhoe.entity.PageResult;
import com.tlu.qlsuckhoe.entity.Thietbiyte;
import com.tlu.qlsuckhoe.service.criteria.ThietbiyteCriteria;

import java.util.List;

public interface ThietbiyteService {

	public Thietbiyte findById(Integer idthietbiyte);

	public List<Thietbiyte> findAll();

	public void delete(Integer idthietbiyte);

	public Thietbiyte create(ThietbiyteCriteria thietbiyte);

	public Thietbiyte update(Integer idthietbiyte,ThietbiyteCriteria thietbiyte);

	public Boolean exist(Thietbiyte thietbiyte);
	
	public PageResult<Thietbiyte> search(int pageNo,int pageSize);
}
