/*
 * Created on 2018-09-27 ( Date ISO 2018-09-27 - Time 09:24:57 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.tlu.qlsuckhoe.service;

import java.util.List;

import javax.transaction.Transactional;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.tlu.qlsuckhoe.entity.PageResult;
import com.tlu.qlsuckhoe.entity.Thuoc;
import com.tlu.qlsuckhoe.repository.ThuocRepository;
import com.tlu.qlsuckhoe.service.criteria.ThuocCriteria;
@Service
@Transactional
public class ThuocServiceImpl implements ThuocService {
	@Autowired
	private ThuocRepository thuocRepository;
	@Autowired
	private LoaithuocServiceImpl loaithuoc;
	@Autowired
	private NhasanxuatServiceImpl nhasx;
	@Override
	public Thuoc findById(Integer idthuoc) {
		return thuocRepository.findOne(idthuoc);
	}

	@Override
	public List<Thuoc> findAll() {
		return thuocRepository.findAllthuoc();
	}

	@Override
	@Transactional
	public void delete(Integer idthuoc) {
		thuocRepository.deleteById(idthuoc);
	}

	@Override
	@Transactional
	public Thuoc create(ThuocCriteria thuoc) {
		// TODO Auto-generated method stub
		Thuoc t= new Thuoc();
		t.setCachdung(thuoc.getCachdung());
		t.setLoaithuoc(loaithuoc.findById(thuoc.getIdloaithuoc()));
		t.setNhasanxuat(nhasx.findById(thuoc.getIdnhasanxuat()));
		t.setNgaynhap(thuoc.getNgaynhap());
		t.setSoluong(thuoc.getSoluong());
		t.setTacdung(thuoc.getTacdung());
		t.setTenthuoc(thuoc.getTenthuoc());
		thuocRepository.save(t);
		return t;
	}

	@Override
	@Transactional
	public Thuoc update(int idthuoc, ThuocCriteria thuoc) {
		Thuoc t = findById(idthuoc);
		t.setCachdung(thuoc.getCachdung());
		t.setLoaithuoc(loaithuoc.findById(thuoc.getIdloaithuoc()));
		t.setNhasanxuat(nhasx.findById(thuoc.getIdnhasanxuat()));
		t.setNgaynhap(thuoc.getNgaynhap());
		t.setSoluong(thuoc.getSoluong());
		t.setTacdung(thuoc.getTacdung());
		t.setTenthuoc(thuoc.getTenthuoc());
		thuocRepository.save(t);
		return t;
	}

	@Override
	public Boolean exist(Thuoc thuoc) {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public PageResult<Thuoc> search(int pageNo, int pageSize) {
		int skip=(pageNo-1)*pageSize;
		int totalRecordCount=(int)thuocRepository.count();
		List<Thuoc> t= thuocRepository.findAllThuocWithPagination(skip,pageSize);
		return new PageResult<Thuoc>(t,pageNo,pageSize,totalRecordCount);
	}

	@Override
	public List<Thuoc> findAllThuocByIdloaithuoc(int idloaithuoc) {
		return thuocRepository.findAllThuocByIdloaithuoc(idloaithuoc);
	}
}

