/*
 * Created on 2018-09-27 ( Date ISO 2018-09-27 - Time 09:24:56 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.tlu.qlsuckhoe.service;

import com.tlu.qlsuckhoe.entity.PageResult;
import com.tlu.qlsuckhoe.entity.Thuoc;
import com.tlu.qlsuckhoe.service.criteria.ThuocCriteria;

import java.util.List;

public interface ThuocService {

	public Thuoc findById(Integer idthuoc);

	public List<Thuoc> findAll();
	
	public List<Thuoc> findAllThuocByIdloaithuoc(int idloaithuoc);

	public void delete(Integer idthuoc);

	public Thuoc create(ThuocCriteria thuoc);

	public Thuoc update(int idthuoc,ThuocCriteria thuoc);

	public Boolean exist(Thuoc thuoc);
	
	public PageResult<Thuoc> search(int pageNo,int pageSize);
}
