/*
 * Created on 2018-09-27 ( Date ISO 2018-09-27 - Time 09:24:57 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.tlu.qlsuckhoe.service;



import java.util.List;
//import java.util.Optional;

import javax.transaction.Transactional;

import com.tlu.qlsuckhoe.repository.TintucRepository;
import com.tlu.qlsuckhoe.entity.PageResult;
import com.tlu.qlsuckhoe.entity.Tintuc;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

@Service
@Transactional
public class TintucServiceImpl implements TintucService {

	@Autowired
	private TintucRepository tintucRepository;

	@Override
	public Tintuc findById(Integer idtintuc) {
		return tintucRepository.findOne(idtintuc);
	}

	@Override
	public Boolean delete(Integer idtintuc) {
		if (findById(idtintuc) != null) {
			tintucRepository.delete(idtintuc);
			return true;
		}
		return false;
	}

	@Override
	public Tintuc create(Tintuc tintuc) {
		return tintucRepository.save(tintuc);
	}

	@Override
	public void update(int idtintuc,Tintuc tintucToUpdate) {
		Tintuc tintuc = findById(idtintuc);
		tintuc.setNgaydang(tintucToUpdate.getNgaydang());
		tintuc.setNoidung(tintucToUpdate.getNoidung());
		tintuc.setTieude(tintucToUpdate.getTieude());
		tintucRepository.save(tintuc);
	}

	@Override
	public Boolean exist(Tintuc tintuc) {
						return tintucRepository.exists(tintuc.getIdtintuc());
																	}

	@Override
	public List<Tintuc> findAll() {
		return tintucRepository.findAll();
	}

	@Override
	public PageResult<Tintuc> search(int page, int pagesize) {
		int skip=(page-1)*pagesize;
		return new PageResult<Tintuc>(tintucRepository.findAllTintucWithPagination(skip,pagesize),page,pagesize,(int)tintucRepository.count());
	}
}

