/*
 * Created on 2018-09-27 ( Date ISO 2018-09-27 - Time 09:24:57 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.tlu.qlsuckhoe.service;

import com.tlu.qlsuckhoe.entity.PageResult;
import com.tlu.qlsuckhoe.entity.Tintuc;
import java.util.List;
//import java.util.Optional;

public interface TintucService {

	public Tintuc findById(Integer idtintuc);

	public List<Tintuc> findAll();
	
	public PageResult<Tintuc> search(int page,int pagesize);
	
	public Boolean delete(Integer idtintuc);

	public Tintuc create(Tintuc tintuc);

	public void update(int idtintuc,Tintuc tintucToUpdate);

	public Boolean exist(Tintuc tintuc);
}
