/*
 * Created on 2018-09-27 ( Date ISO 2018-09-27 - Time 09:24:57 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.tlu.qlsuckhoe.service;

import com.tlu.qlsuckhoe.entity.PageResult;
import com.tlu.qlsuckhoe.entity.Yte;
import com.tlu.qlsuckhoe.service.criteria.YteCriteria;

import java.util.List;

public interface YteService {

	public Yte findById(Integer idyte);

	public List<Yte> findAll();

	public void delete(Integer idyte);

	public Yte create(YteCriteria yte);

	public Yte update(int idyte,YteCriteria yte);

	public Boolean exist(Yte yte);
	
	public PageResult<Yte> search(int pageNo,int pageSize);
}
