/*
 * Created on 2018-09-27 ( Date ISO 2018-09-27 - Time 09:24:56 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.tlu.qlsuckhoe.service.criteria;


/**
 * Criteria bean used for Thietbiyte search.
 * @author Telosys (http://www.telosys.org/) version 3.0.0
 */
public class ThietbiyteCriteria {
	private int idthietbiyte;
	private int idnhasanxuat;
    private String tenthietbi; 
    private String ngaynhap;
    private int soluong;
    private String cachdung; 
	// Constructor
	public ThietbiyteCriteria() {
		// Needed empty constructor for serialization
	}
	
	public int getIdthietbiyte() {
		return idthietbiyte;
	}

	public void setIdthietbiyte(int idthietbiyte) {
		this.idthietbiyte = idthietbiyte;
	}

	public void setTenthietbi(String tenthietbi) {this.tenthietbi = tenthietbi;}
	public String getTenthietbi() {return this.tenthietbi;}
	public void setCachdung(String cachdung) {this.cachdung = cachdung;}
	public String getCachdung() {return this.cachdung;}
	
	public int getIdnhasanxuat() {
		return idnhasanxuat;
	}

	public void setIdnhasanxuat(int idnhasanxuat) {
		this.idnhasanxuat = idnhasanxuat;
	}

	public String getNgaynhap() {
		return ngaynhap;
	}

	public void setNgaynhap(String ngaynhap) {
		this.ngaynhap = ngaynhap;
	}

	public int getSoluong() {
		return soluong;
	}

	public void setSoluong(int soluong) {
		this.soluong = soluong;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder(); 
		sb.append(tenthietbi); 
		sb.append("|"); 
		sb.append(cachdung); 
        return sb.toString();
	}
}
