/*
 * Created on 2018-09-27 ( Date ISO 2018-09-27 - Time 09:24:57 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.tlu.qlsuckhoe.service.criteria;

/**
 * Criteria bean used for Thuoc search.
 * @author Telosys (http://www.telosys.org/) version 3.0.0
 */
public class ThuocCriteria {
	private int idthuoc;
	private int idloaithuoc;
	private int idnhasanxuat;
    private String tenthuoc; 
    private String tacdung; 
    private String cachdung; 
    private String ngaynhap; 
    private int soluong;
	// Constructor
	public ThuocCriteria() {
		// Needed empty constructor for serialization
	}
	
	public int getIdthuoc() {
		return idthuoc;
	}

	public void setIdthuoc(int idthuoc) {
		this.idthuoc = idthuoc;
	}

	public int getIdloaithuoc() {
		return idloaithuoc;
	}

	public void setIdloaithuoc(int idloaithuoc) {
		this.idloaithuoc = idloaithuoc;
	}

	public int getIdnhasanxuat() {
		return idnhasanxuat;
	}

	public void setIdnhasanxuat(int idnhasanxuat) {
		this.idnhasanxuat = idnhasanxuat;
	}

	public int getSoluong() {
		return soluong;
	}

	public void setSoluong(int soluong) {
		this.soluong = soluong;
	}

	public void setTenthuoc(String tenthuoc) {this.tenthuoc = tenthuoc;}
	public String getTenthuoc() {return this.tenthuoc;}
	public void setTacdung(String tacdung) {this.tacdung = tacdung;}
	public String getTacdung() {return this.tacdung;}
	public void setCachdung(String cachdung) {this.cachdung = cachdung;}
	public String getCachdung() {return this.cachdung;}
	public void setNgaynhap(String ngaynhap) {this.ngaynhap = ngaynhap;}
	public String getNgaynhap() {return this.ngaynhap;}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder(); 
		sb.append(tenthuoc); 
		sb.append("|"); 
		sb.append(tacdung); 
		sb.append("|"); 
		sb.append(cachdung); 
		sb.append("|"); 
		sb.append(ngaynhap); 
        return sb.toString();
	}
}
